### ISSUE TITLE
Unhandled TypeError When Click+ Drag Either Axis on Plot Customization Example

### ISSUE THREAD

**Issue by j9ac9k** [pyqtgraph/pyqtgraph#1277]
### Short description
TypeError Exception Generated When Clicking + Dragging on an Axis on `customPlot.py` example

### Code to reproduce

```
python -m pyqtgraph.examples
```

Select Custom Plot example, run it, click + drag the horizontal or vertical axis.

### Expected behavior
Axis should move (this occurs in other examples)

### Real behavior
Unhandled TypeError occurs

```
    |==============================>>
    |  Traceback (most recent call last):
    |    File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\examples\customPlot.py", line 50, in <module>
    |      QtGui.QApplication.instance().exec_()
    |    File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\widgets\GraphicsView.py", line 376, in mouseMoveEvent
    |      QtGui.QGraphicsView.mouseMoveEvent(self, ev)
    |    File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\GraphicsScene\GraphicsScene.py", line 195, in mouseMoveEvent
    |      if self.sendDragEvent(ev, init=init):
    |    File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\GraphicsScene\GraphicsScene.py", line 313, in sendDragEvent
    |      debug.printExc("Error sending drag event:")
    |    --- exception caught here ---
    |    File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\GraphicsScene\GraphicsScene.py", line 311, in sendDragEvent
    |      item.mouseDragEvent(event)
    |    File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\graphicsItems\AxisItem.py", line 1191, in mouseDragEvent
    |      return lv.mouseDragEvent(event, axis=0)
    |  TypeError: mouseDragEvent() got an unexpected keyword argument 'axis'
    |==============================<<
```

### Tested environment(s)

 * PyQtGraph version: 0.11.0 - current master branch ( b41c4a71e54006e51808bc9fdba8ccf342526955 )
 * Qt Python binding: 'PyQt5 5.15.0 Qt 5.15.0'
 * Python version:  3.7.7
 * NumPy version: 1.18.5
 * Operating system:  Windows 10
 * Installation method: pip

### Additional context

I attempted to git bisect this momentarily, but saw this issue was present even in 0.10.0, so this is definitely not something new!

**Comment by ixjlyons** [comment]
Looks like the `CustomViewBox` in the example just needs to be updated.

https://github.com/pyqtgraph/pyqtgraph/blob/b41c4a71e54006e51808bc9fdba8ccf342526955/examples/customPlot.py#L25

**Comment by j9ac9k** [comment]
I stumbled across this in the most random way, I was looking to test #1276 when I came across this ...I was really confused, but when I noticed how long the issue has been around for, ...what dumb luck!
