### ISSUE TITLE
pen parameter type broken by df3e213

### ISSUE THREAD

**Issue by marty-dy** [pyqtgraph/pyqtgraph#2920]
Cap Style and Join Style no longer work on a parameter tree pen type. Editing either parameter results in AttributeErrors.

### Steps to reproduce

1. Run `python -m pyqtgraph.examples.parametertree`
2. Edit Cap Style or Join Style

### Expected behavior
Cap Style or Join Style should change and print their value to the console

### Real behavior

```
Traceback (most recent call last):
  File "pyqtgraph\parametertree\parameterTypes\pen.py", line 207, in penPropertySetter
    getattr(boundPen.__class__, setName)(boundPen, value)
AttributeError: type object 'PySide2.QtGui.QPen' has no attribute 'setCapstyle'
Traceback (most recent call last):
  File "pyqtgraph\parametertree\parameterTypes\pen.py", line 207, in penPropertySetter
    getattr(boundPen.__class__, setName)(boundPen, value)
```

### Tested environment(s)

 * PyQtGraph version: master
 * Qt Python binding: PySide2 5.15.8 Qt 5.15.8
 * Python version: 3.9.18
 * NumPy version: 1.26.2
 * Operating system: Windows
 * Installation method: download

**Comment by marty-dy** [comment]
I think the issue is caused by https://github.com/pyqtgraph/pyqtgraph/blob/261a32515fac2ffd5071801ef4b69720828b5142/pyqtgraph/parametertree/parameterTypes/pen.py#L204 since `capitalize` makes the rest of the string lower case.

**Comment by pijyoi** [comment]
Thank you for identifying this issue. PR #2853 would fix this bug.

**Comment by pijyoi** [comment]
For the record, #2734 is the offending PR that made this bug.

**Comment by pijyoi** [comment]
This has been fixed in the 0.13.4 release
