### ISSUE TITLE
'SymbolAtlas' object has no attribute 'symbolMap'

### ISSUE THREAD

**Issue by danielhrisca** [pyqtgraph/pyqtgraph#1490]
Trying to use a scatter plot this issue is raised.
This works in pyqtgraph 0.11.0

### Code to reproduce

```python
import pyqtgraph as pg
import numpy as np
```

### Real behavior

```
<class 'AttributeError'>	 
'SymbolAtlas' object has no attribute 'symbolMap'
--------------------------------------------------------------------------------
  File "asammdf\gui\widgets\mdi_area.py", line 487, in add_window
  File "asammdf\gui\widgets\plot.py", line 744, in __init__
  File "asammdf\gui\widgets\plot.py", line 1590, in __init__
  File "pyqtgraph\graphicsItems\PlotDataItem.py", line 161, in __init__
  File "pyqtgraph\graphicsItems\ScatterPlotItem.py", line 407, in __init__
  File "pyqtgraph\graphicsItems\ScatterPlotItem.py", line 469, in setData
  File "pyqtgraph\graphicsItems\ScatterPlotItem.py", line 591, in addPoints
  File "asammdf\gui\__init__.py", line 28, in updateSpots
```

### Tested environment(s)

 * PyQtGraph version: 0.11.1
 * Qt Python binding: 5.15.2
 * Python version: 
 * NumPy version: 
 * Operating system: 
 * Installation method:

**Comment by danielhrisca** [comment]
Actually that was in a patched function
