### PR TITLE
Fix ParameterTree.clear()

### LINKED ISSUE #731: GITHUB pyqtgraph error : 'NoneType' object has no attribute 'setFirstItemColumnSpanned'
Considering your last comment on using the latest from GITHUB, I tried using the latest package and see the following traceback. My parameter tree may have an error? However the same paramtertree setup works with pyqtgraph 0.10.0.

Python 3.5.4, PyQt 5.11.2, pyqtgraph (2018-07-22)

```
  File "lib\_test\test.py", line 629, in <module>
    p.setup_map_control(d)
  File "lib\_test\test.py", line 490, in setup_map_control
    t.setParameters(self.ptree1, showTop=False)
  File "lib\pyqtgraph\parametertree\ParameterTree.py", line 46, in setParameters
    self.clear()
  File "lib\pyqtgraph\parametertree\ParameterTree.py", line 83, in clear
    self.invisibleRootItem().takeChildren()
  File "lib\pyqtgraph\widgets\TreeWidget.py", line 392, in takeChildren
    TreeWidget.informTreeWidgetChange(child)
  File "lib\pyqtgraph\widgets\TreeWidget.py", line 172, in informTreeWidgetChange
    item.treeWidgetChanged()
  File "lib\pyqtgraph\parametertree\parameterTypes.py", line 429, in treeWidgetChanged
    self.treeWidget().setFirstItemColumnSpanned(self, True)
AttributeError: 'NoneType' object has no attribute 'setFirstItemColumnSpanned'
```

### PR DESCRIPTION
**Pull request by campagnola**
Fixes #731

### CODE REVIEW

**Comment by campagnola** [comment]
Whoops, wrong base..

**Comment by j9ac9k** [comment]
Thanks @campagnola this looks great to me.  Merging!
