### PR TITLE
Fix ViewBox axis zoom in RectMode and examples/customPlot.py

### LINKED ISSUE #1277: Unhandled TypeError When Click+ Drag Either Axis on Plot Customization Example
### Short description
TypeError Exception Generated When Clicking + Dragging on an Axis on `customPlot.py` example

### Code to reproduce

```
python -m pyqtgraph.examples
```

Select Custom Plot example, run it, click + drag the horizontal or vertical axis.

### Expected behavior
Axis should move (this occurs in other examples)

### Real behavior
Unhandled TypeError occurs

```
    |==============================>>
    |  Traceback (most recent call last):
    |    File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\examples\customPlot.py", line 50, in <module>
    |      QtGui.QApplication.instance().exec_()
    |    File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\widgets\GraphicsView.py", line 376, in mouseMoveEvent
    |      QtGui.QGraphicsView.mouseMoveEvent(self, ev)
    |    File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\GraphicsScene\GraphicsScene.py", line 195, in mouseMoveEvent
    |      if self.sendDragEvent(ev, init=init):
    |    File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\GraphicsScene\GraphicsScene.py", line 313, in sendDragEvent
    |      debug.printExc("Error sending drag event:")
    |    --- exception caught here ---
    |    File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\GraphicsScene\GraphicsScene.py", line 311, in sendDragEvent
    |      item.mouseDragEvent(event)
    |    File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\pyqtgraph\graphicsItems\AxisItem.py", line 1191, in mouseDragEvent
    |      return lv.mouseDragEvent(event, axis=0)
    |  TypeError: mouseDragEvent() got an unexpected keyword argument 'axis'
    |==============================<<
```

### Tested environment(s)

 * PyQtGraph version: 0.11.0 - current master branch ( b41c4a71e54006e51808bc9fdba8ccf342526955 )
 * Qt Python binding: 'PyQt5 5.15.0 Qt 5.15.0'
 * Python version:  3.7.7
 * NumPy version: 1.18.5
 * Operating system:  Windows 10
 * Installation method: pip

### Additional context

I attempted to git bisect this momentarily, but saw this issue was present even in 0.10.0, so this is definitely not something new!

### PR DESCRIPTION
**Pull request by 2xB**
For `ViewBox`, this PR fixes left-click-drag on an axis when the `ViewBox` is in `RectMode`. To try it out, here is a modified version of `customPlot.py`, just left-click-drag on the x or y axis:

```python3
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore, QtGui
import numpy as np
import time

class CustomViewBox(pg.ViewBox):
    def __init__(self, *args, **kwds):
        kwds['enableMenu'] = False
        pg.ViewBox.__init__(self, *args, **kwds)
        self.setMouseMode(self.RectMode)
        
    ## reimplement right-click to zoom out
    def mouseClickEvent(self, ev):
        if ev.button() == QtCore.Qt.RightButton:
            self.autoRange()


app = pg.mkQApp()

axis = pg.DateAxisItem(orientation='bottom')
vb = CustomViewBox()

pw = pg.PlotWidget(viewBox=vb, axisItems={'bottom': axis}, enableMenu=False, title="PlotItem with DateAxisItem and custom ViewBox<br>Menu disabled, mouse behavior changed: left-drag to zoom, right-click to reset zoom")
dates = np.arange(8) * (3600*24*356)
pw.plot(x=dates, y=[1,6,2,4,3,5,6,8], symbol='o')
pw.show()
pw.setWindowTitle('pyqtgraph example: customPlot')

r = pg.PolyLineROI([(0,0), (10, 10)])
pw.addItem(r)

## Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()

```

For `examples/customPlot.py`, this PR
  * updates the method to disable the right-click menu, using `ViewBox.enableMenu`, a feature of PyQtGraph instead of a monkey-patch.
  * shows how to monkey-patch `mouseDragEvent` anyways in case someone wants to e.g. disable continuous zoom via right-click-drag on an axis. This might come in handy e.g. in case of complicated rebinning after zooming

Fixes #1277

### CODE REVIEW

**Comment by j9ac9k** [comment]
Thanks for the PR @2xB LGTM, merging.
