### ISSUE TITLE
Pyqtgraph not working in Python 3.8 [bug]

### ISSUE THREAD

**Issue by edusanvaz** [pyqtgraph/pyqtgraph#1096]
It seems that in Python 3.8, package time does not implement 'clock' class, since it was deprecated in prvious versions. The error message when importing Pyqtgraph is:

AttributeError: module 'time' has no attribute 'clock'

I think it could be fixed quite easy.

Best regards,
Eduardo Santamaría Vázquez.

**Comment by Dschoni** [comment]
Fixed in #980
